/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qlvkwacedvkgywxemzut"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsdmt3YWNlZHZrZ3l3eGVtenV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MjM1NzAsImV4cCI6MjA3OTQ5OTU3MH0.KHxxGkY6usrjWmdWtFa26BJAc7gSPhR_UqZ5ZjwFXf8"

